### ISSUE TITLE
test-zkapp.aurowallet.com => Application error

### ISSUE THREAD

**Issue by SvenMeyer** [aurowallet/auro-wallet-browser-extension#40]
On the website [https://www.aurowallet.com/](https://www.aurowallet.com/) I clicked the link to `Test zkApp` in the footer, which lead me to [https://test-zkapp.aurowallet.com/](https://test-zkapp.aurowallet.com/) , however there I just got briefly some input fields and text (totally unformatted), then ended up with a blank web page with the message :

`Application error: a client-side exception has occurred (see the browser console for more information).`

Chrome browser console had these messages :+1: 

```
initNetwork== undefined
framework-0073b5da5bf4cc6a.js:194 TypeError: Cannot read properties of undefined (reading 'networkID')
    at Home (index-74e3c2ceb2a347d1.js:1866:69)
    at Nh (framework-0073b5da5bf4cc6a.js:166:137)
    at cj (framework-0073b5da5bf4cc6a.js:202:258)
    at Vk (framework-0073b5da5bf4cc6a.js:297:88)
    at Uk (framework-0073b5da5bf4cc6a.js:285:389)
    at Tk (framework-0073b5da5bf4cc6a.js:285:320)
    at Ik (framework-0073b5da5bf4cc6a.js:285:180)
    at Nk (framework-0073b5da5bf4cc6a.js:276:88)
    at Gk (framework-0073b5da5bf4cc6a.js:273:429)
    at J (framework-0073b5da5bf4cc6a.js:471:203)
    at MessagePort.R (framework-0073b5da5bf4cc6a.js:472:128)
Li @ framework-0073b5da5bf4cc6a.js:194
main-c84ee0693d97f453.js:650 TypeError: Cannot read properties of undefined (reading 'networkID')
    at Home (index-74e3c2ceb2a347d1.js:1866:69)
    at Nh (framework-0073b5da5bf4cc6a.js:166:137)
    at cj (framework-0073b5da5bf4cc6a.js:202:258)
    at Vk (framework-0073b5da5bf4cc6a.js:297:88)
    at Uk (framework-0073b5da5bf4cc6a.js:285:389)
    at Tk (framework-0073b5da5bf4cc6a.js:285:320)
    at Ik (framework-0073b5da5bf4cc6a.js:285:180)
    at Nk (framework-0073b5da5bf4cc6a.js:276:88)
    at Gk (framework-0073b5da5bf4cc6a.js:273:429)
    at J (framework-0073b5da5bf4cc6a.js:471:203)
    at MessagePort.R (framework-0073b5da5bf4cc6a.js:472:128)
renderError @ main-c84ee0693d97f453.js:650
main-c84ee0693d97f453.js:651 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
renderError @ main-c84ee0693d97f453.js:651
```

**Comment by lvshaoping007** [comment]
This is caused by some exceptions when communicating with the Auro Wallet. I have added the log and checking this.

**Comment by lvshaoping007** [comment]
Hello, we fixed this. Thank you!
